using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class Graph : MonoBehaviour
{

    //private Dictionary<string, GameObject> m_Graph;
    //private List<GameObject> m_Components;
    //private List<(string, string)> m_ComponentEdges;

    //private List<string> m_Clusters;
    private List<GraphComponent> m_Components;



    // Start is called before the first frame update
    void Start()
    {
        //foreach identified comopnent in graph, create component object with id and list of ids
        //m_Components[i] = Instantiate() as GraphComponent;
        //m_Components[i].Init(i, ids));

        ComponentLoop();

    }

    // Update is called once per frame
    void Update()
    {

    }

    void ComponentLoop()
    {
        //m_ComponentEdges = new List<(string, string)>();
        //for (int i = 0; i < m_Components.Count; i++)
        //{
        //    for (int j = i + 1; j < m_Components.Count; j++)
        //    {
        //        var rep1 = m_Components[i].GetComponent<GraphComponent>().GetRepresentatives();
        //        var rep2 = m_Components[j].GetComponent<GraphComponent>().GetRepresentatives();

        //        InitSprings(rep1, rep2);
        //    }
        //}
    }

    private void InitSprings(List<string> rep1, List<string> rep2)
    {
        //var len = Math.Max(rep1.Count, rep2.Count);

        //for (int i = 0; i < len; i++)
        //{
        //    for (int j = i + 1; j < len; j++)
        //    {
        //        m_ComponentEdges.Add((rep1[i], rep2[j]));
        //    }
        //}
    }

    private void FixedUpdate()
    {
        // foreach component in m_Components
        // for each component in m_Comonents
        // foreach spring between 3 chosen clusters in each component
        // spring.applyforce()

        //foreach ((var node1, var node2) in m_ComponentEdges)
        //{

        //}
    }
}
